refactor: script cleanup

diff --git a/lib/video2gif b/lib/video2gif
--- a/lib/video2gif
+++ b/lib/video2gif
@@ -51,10 +51,14 @@ print_version() {
   echo "video2gif $version"
 }
 
+print_error() {
+  printf "\nerror: %s\n\n" "$@" >&2
+}
+
 check_argument() {
   if [ -z "$2" ]
   then
-    echo "value for '$1' not provided" >&2
+    print_error "value for '$1' not provided"
     exit 1
   fi
 }
@@ -65,8 +69,7 @@ handle_with_docker() {
   shift
   shift
 
-  while [ "$#" -gt 0 ]
-  do
+  while [ "$#" -gt 0 ]; do
     case "$1" in
       -i|--input|-o|--output)
         shift
@@ -84,15 +87,13 @@ handle_with_docker() {
   input_dirname=$(get_absolute_path $input_file)
   output_dirname=$(get_absolute_path $output_file)
 
-  if [ -z "$input_dirname" ]
-  then
-    echo "input file ${input_file} does not exist"
+  if [ -z "$input_dirname" ]; then
+    print_error "input file ${input_file} does not exist"
     exit 1
   fi
 
-  if [ -z "$output_dirname" ]
-  then
-    echo "output directory for ${output_file} does not exist"
+  if [ -z "$output_dirname" ]; then
+    print_error "output directory for ${output_file} does not exist"
     exit 1
   fi
 
@@ -104,9 +105,7 @@ handle_with_docker() {
 }
 
 all_parameters=$@
-
-while [ "$#" -gt 0 ]
-do
+while [ "$#" -gt 0 ]; do
   case "$1" in
     -h|--help)
       print_help
@@ -153,7 +152,7 @@ do
       shift
       ;;
     -te|--end-time)
-    end_time="$2"
+      end_time="$2"
       check_argument $1 $2
       shift
       shift
@@ -163,7 +162,7 @@ do
       break
       ;;
     -*)
-      echo "Invalid option '$1'." >&2
+      print_error "invalid option '$1'."
       print_usage
       exit 1
       ;;
@@ -171,65 +170,45 @@ do
   esac
 done
 
-if [ "$#" -eq 0 ] && [ -z "$input_file" ]
-then
-  echo "input not provided" >&2
-  echo ""
+if [ "$#" -eq 0 ] && [ -z "$input_file" ]; then
+  print_error "input not provided"
   print_help
   exit 1
 fi
 
-if [ "$#" -gt 1 ] || ([ "$#" -gt 0 ] && [ ! -z "$input_file" ])
-then
-  echo "command doesn't accept multiple inputs" >&2
-  echo ""
+if [ "$#" -gt 1 ] || ([ "$#" -gt 0 ] && [ ! -z "$input_file" ]); then
+  print_error "command doesn't accept multiple inputs"
   print_help
   exit 1
 fi
 
-if [ -z "$input_file" ]
-then
+if [ -z "$input_file" ]; then
   input_file=$@
 fi
 
-if [ -z "$output_file" ]
-then
+if [ -z "$output_file" ]; then
   output_filename=$(get_output_filename $input_file)
 else
   output_filename=$output_file
 fi
 
 if [ -x "$(command -v ffmpeg)" ] && [ -x "$(command -v gifsicle)" ]; then
-  echo 'using ffmpeg + gifsicle'
-  if [ -n "$output_size" ]
-  then
-    output_size_parameter="-s $output_size"
-  fi
-
-  if [ -n "$start_time" ]
-  then
-    start_time_parameter="-ss $start_time"
-  fi
-
-  if [ -n "$end_time" ]
-  then
-    end_time_parameter="-to $end_time"
-  fi
+  [ -n "$output_size" ] && output_size_parameter="-s $output_size"
+  [ -n "$start_time" ] && start_time_parameter="-ss $start_time"
+  [ -n "$end_time" ] && end_time_parameter="-to $end_time"
 
   echo "converting $input_file to $output_filename..."
 
-  ffmpeg $start_time_parameter $end_time_parameter -i $input_file $output_size_parameter -r $frame_rate -f gif  - | \
-  gifsicle --optimize=3 --delay=$delay_between_frames > $output_filename
+  ffmpeg $start_time_parameter $end_time_parameter \
+    -i $input_file $output_size_parameter -r $frame_rate -f gif  - | \
+    gifsicle --optimize=3 --delay=$delay_between_frames > $output_filename
 
-  echo ""
-  echo "SUCCESS: $input_file converted"
-  echo ""
+  printf "\nSUCCESS: $input_file converted\n\n"
+
 elif [ -x "$(command -v docker)" ]; then
-  echo "using docker with image ${version}"
   handle_with_docker $input_file $output_filename $all_parameters
 else
-  echo "couldn't find required dependencies."
-  echo "this script requires docker OR ffmpeg and gifsicle."
+  print_error "couldn't find required dependencies. \nthis script requires docker OR ffmpeg and gifsicle.\n"
   exit 1
 fi
 
